Repository macgorithm/live4mac, pull requests merged in 2022-05, with the labels that each got.

#51 1253 좋다, 2980 도로와신호등 (예원)
  2022/May/week_1/boj_1253_좋다_이예원.java
  2022/May/week_1/boj_2980_도로와신호등_이예원.java
Labels: 🐶 이예원, 구현, 투포인터

#50 1253 좋다, 2980 도로와신호등 (늘이)
  2022/May/week_1/boj_1253_좋다_하늘이.swift
  2022/May/week_1/boj_1280_도로와신호등_하늘이.swift
Labels: 🐯 하늘이, 구현

#52 Chore: May week2 폴더 추가
  2022/May/week_2/test.java
Labels: 🐶 이예원, 구현, 투포인터

#49 1253 좋다, 2980 도로와신호등 (수연)
  2022/May/week_1/boj_1253_좋다_손수연.java
  2022/May/week_1/boj_1280_도로와신호등_손수연.java
Labels: 🦋 손수연, 구현, 투포인터

#48 1253 좋다, 2980 도로와신호등 (혜안)
  2022/May/week_1/boj_1253_좋다_경혜안.java
  2022/May/week_1/boj_2980_도로와신호등_경혜안.java
Labels: 🐰 경혜안, 구현, 투포인터

#55 10881 프로도의선물포장, 프로그래머스 신규아이디추천, 프로그래머스 표편집 (수연)
  2022/May/week_2/boj_10881_프로도의선물포장_손수연.java
  2022/May/week_2/프로그래머스_신규아이디추천_손수연.java
  2022/May/week_2/프로그래머스_표편집_손수연.java
Labels: 🦋 손수연, 문자열, 브루트포스 알고리즘, 정규식, STACK/QUEUE

#54 10881 프로도의선물포장, 프로그래머스 신규아이디추천, 프로그래머스 표편집 (늘이)
  2022/May/week_2/boj_10881_프로도의선물포장_하늘이.swift
  2022/May/week_2/프로그래머스_lv1_신규아이디추천_하늘이.swift
  2022/May/week_2/프로그래머스_lv3_표편집_하늘이.swift
Labels: 🐯 하늘이, 구현, 문자열, 브루트포스 알고리즘

#59 프로그래머스 오픈채팅방, 1261 알고스팟 (늘이)
  2022/May/week_3/boj_1261_알고스팟_하늘이.swift
  2022/May/week_3/프로그래머스_lv2_오픈채팅방_하늘이.swift
Labels: 🐯 하늘이, BFS/DFS, 다익스트라, Hash

#61 프로그래머스 오픈채팅방, 1261 알고스팟 (예원)
  2022/May/week_3/boj_1261_알고스팟_이예원.java
  2022/May/week_3/프로그래머스_Lv2_오픈채팅방_이예원.java
Labels: 🐶 이예원, BFS/DFS, 다익스트라, Hash

#60 프로그래머스 오픈채팅방, 1261 알고스팟 (수연)
  2022/May/week_3/boj_1261_알고스팟_손수연.java
  2022/May/week_3/프로그래머스_lv2_오픈채팅방_손수연.java
Labels: 🦋 손수연, BFS/DFS, 다익스트라, Hash
