Repository macgorithm/live4mac, pull requests merged in 2022-08, with the labels that each got.

#84 프로그래머스 괄호변환, boj 여왕벌 (예원)
  2022/Jul/week_1/프로그래머스_Lv2_괄호변환_이예원.java
Labels: 🐶 이예원, 문자열, STACK/QUEUE

#82 프로그래머스 기능개발, 괄호 변환 , boj 여왕벌(혜안)
  2022/Jun/week4/boj_10836_여왕벌_경혜안.java
  2022/Jun/week4/프로그래머스_lv2_괄호변환_경혜안.java
  2022/Jun/week4/프로그래머스_lv2_기능개발_경혜안.java
Labels: 🐰 경혜안, 구현, STACK/QUEUE

#85 Code: Solve 프로그래머스 행렬테두리회전하기 (혜안)
  2022/Aug/week1/프로그래머스_lv2_행렬테두리회전하기_경혜안.java
Labels: 🐰 경혜안, 구현, 😂 못풀었어요

#87 프로그래머스 행렬 테두리 회전하기, boj 물통 (수연)
  2022/Aug/week_4/boj_2251_물통_손수연.java
  2022/Aug/week_4/프로그래머스_lv2_77485_행렬테두리회전하기_손수연.java
  2022/Aug/week_5/boj_21608_상어초등학교_손수연.java
  2022/Aug/week_5/프로그래머스_lv2_두큐합같게만들기_손수연.java
Labels: 🦋 손수연, 구현, BFS/DFS

#89 프로그래머스 두 큐 합 같게 만들기, boj 상어초등학교 (늘이)
  2022/Aug/week_5/boj_21608_상어초등학교_하늘이.swift
  2022/Aug/week_5/프로그래머스_lv2_두큐합같게만들기_하늘이.swift
Labels: 🐯 하늘이, 구현, 투포인터
